# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.14.0]

    steps:
    - uses: actions/checkout@v2


    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}


    # - run: npm ci
    # - run: npm run build --if-present


    # - name: Now zip the npm build
    #   uses: papeloto/action-zip@v1
    #   with:
    #     files: build/
    #     dest: annotate-it-latest-release.zip


    # - name: Automated Version Bump
    #   uses: phips28/gh-action-bump-version@master
    #   with:
    #     tag-prefix: ''
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    # - name: Now get the new version in package.json
    #   id: package-version
    #   uses: martinbeentjes/npm-get-version-action@master


    # - name: Make release
    #   uses: marvinpinto/action-automatic-releases@latest
    #   with:
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     prerelease: true
    #     automatic_release_tag: v${{ steps.package-version.outputs.current-version}}
    #     files: |
    #       annotate-it-latest-release.zip
          
