name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: Install dependencies and run webpack
      run: |
        npm install --silent
        npm run build

    - name: Automated Version Bump
      uses: phips28/gh-action-bump-version@master
      with:
        tag-prefix: ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Now get the new version in package.json
    #   id: package-version
    #   uses: martinbeentjes/npm-get-version-action@master

    - name: Now get the new version in package.json
      id: package-version
      uses: pchynoweth/action-get-npm-version@master

    - name: Now change the current version in the manifest
      run: sed -i 's/🚀 PROD — Annotate it!/Annotate it! v${{ steps.package-version.outputs.version}}/' build/manifest.json

    - name: Now zip the npm build
      uses: papeloto/action-zip@v1
      with:
        files: build/
        dest: annotate-it-v${{ steps.package-version.outputs.version}}.zip

    - name: Make release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: false
        automatic_release_tag: v${{ steps.package-version.outputs.version}}
        files: |
          annotate-it-v${{ steps.package-version.outputs.version}}.zip
          
